app/request/forms.py
"""
.. module:: request.forms.

   :synopsis: Defines forms used to manage procurement requests
"""
from flask_wtf import Form
from wtforms import StringField, SelectField, TextAreaField, BooleanField, HiddenField, SubmitField, DecimalField, \
    IntegerField
from flask_wtf.file import FileField
from wtforms.validators import DataRequired, Length, Email, Regexp, Optional
from wtforms_alchemy import PhoneNumberField
from app.constants import status
import re

funding = [
    ('', ''),
    ('Expense', 'Expense'),
    ('MAARF', 'MAARRF'),
    ('Grant', 'Grant'),
    ('SARA', 'SARA'),
    ('KOCH', 'KOCH'),
    ('Other', 'Other')
]

regexp_message = "Must only contain alphanumeric characters or the following " \
                 "characters: ' ,-."


class CommentForm(Form):
    """Form for creating a new comment."""
    content = TextAreaField(validators=[Length(0, 500), DataRequired('Please enter a comment')])
    file = FileField(u'Upload File...')
    submit = SubmitField(u'Add Comment')


class RequestForm(Form):
    """Form for creating a new request."""
    item = TextAreaField(u'Item*(required)', validators=[
        DataRequired('Please enter the item')])
    quantity = IntegerField(u'Quantity*', validators=[
        DataRequired('Please enter the quantity (only numbers are allowed)')])
    unit_price = DecimalField(u'Price per item*', validators=[
        DataRequired('Please enter the price per item (only numbers are allowed)')])
    total_cost = DecimalField(u'Total price*', validators=[
        DataRequired('Please enter the total price (only numbers are allowed)')])
    funding_source = SelectField(u'Funding*', choices=funding, validators=[
        DataRequired('Please select the funding source')])
    funding_source_description = StringField(u'Funding Other')
    grant_name = StringField(u'Grant Name')
    project_name = StringField(u'Project Name')
    justification = TextAreaField(u'Justification*(required)', validators=[
        DataRequired('You must enter a justification for your request'), Length(1, 500)])
    request_vendor_dropdown = SelectField(u'Vendor Information*')
    request_vendor_name = StringField(u'Vendor Name', validators=[Length(5),
                                                                  Regexp("^[\w, '-.]+$", message=regexp_message),
                                                                  Optional()])
    request_vendor_address = StringField(u'Vendor Address', validators=[Length(5),
                                                                        Regexp("^[\w, '-.]+$", message=regexp_message),
                                                                        Optional()])
    request_vendor_phone = PhoneNumberField(region='US', display_format='national')
    request_vendor_fax = PhoneNumberField(region='US', display_format='national')
    request_vendor_email = StringField(u'Email', validators=[Email(), Optional()])
    request_vendor_taxid = StringField(u'Vendor Tax ID')
    request_vendor_mwbe = BooleanField(u'mwbe')
    submit = SubmitField(u'Submit Request')

    def __init__(self, *args, **kwargs):
        """Fill the vendor dropdown with values from the database upon initialization"""
        super(RequestForm, self).__init__(*args, **kwargs)

        from app.models import Vendor
        vendors = Vendor.query.filter_by(enabled=True).order_by(Vendor.name).all()
        vendor_dropdown = [
            ('default', 'Select Vendor or Enter New Vendor Below')
        ]
        for vendor in vendors:
            vendor_dropdown.append((str(vendor.id), vendor.name))
        self.request_vendor_dropdown.choices = vendor_dropdown


    def validate(self):
        if not Form.validate(self):
            return False

        # check if user selected other and filled out the field
        if self.funding_source.data == "Other" and not self.funding_source_description.data:
            self.funding_source.errors.append("You must specify if you entered Other")
            return False

        # check if user selected grant and filled out the fields
        if self.funding_source.data == "Grant" and (not self.grant_name.data or not self.project_name.data):
            self.funding_source.errors.append("You must include a grant and project name if you entered Grant")
            return False

        if self.request_vendor_dropdown.data == "default":
            # check if user filled out the vendor fields
            if not (self.request_vendor_name.data and self.request_vendor_address.data and
                    self.request_vendor_address.data and self.request_vendor_phone.data and
                    self.request_vendor_fax.data and self.request_vendor_email.data and
                    self.request_vendor_taxid.data):
                self.request_vendor_dropdown.errors.append("You must fill out all fields for Vendor Information")
                return False

        return True


class DeleteCommentForm(Form):
    """Form for deleting a comment."""
    request_id = HiddenField()
    comment_id = HiddenField()
    submit = SubmitField(u'Delete')


class StatusForm(Form):
    """Form for updating status of a request."""
    status = SelectField(u'Status', validators=[DataRequired()])
    submit = SubmitField(u'Update')

app/request/__init__.py
from flask import Blueprint

request = Blueprint('request', __name__, url_prefix='/requests')

from . import views

app/request/views.py
"""
.. module:: request.views.

   :synopsis: Provides routes for managing a specific request
"""
import datetime
import os
from flask import (
    render_template,
    request as flask_request,
    abort,
    redirect,
    url_for,
    send_from_directory,
    current_app,
    flash
)
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from app import db
from app.email_notification import send_email
from app.errors import flash_errors
from app.request.forms import RequestForm, CommentForm, DeleteCommentForm, StatusForm
from app.models import Request, User, Vendor, Comment
from app.request import request as request
from app.constants import roles, status, mimetypes
from app.request.utils import determine_fiscal_id, email_setup


@request.route('/', methods=['GET', 'POST'])
@login_required
def display_requests():
    """Return requests page that displays all requests."""
    if current_user.role == roles.ADMIN:
        requests = Request.query.order_by(Request.date_submitted.desc()).all()
    else:
        requests = Request.query.filter_by(division=current_user.division).order_by(Request.date_submitted.desc()).all()
    return render_template('request/requests.html', requests=requests)


@request.route('/new', methods=['GET', 'POST'])
@login_required
def new_request():
    """Return new request form for procurements."""
    form = RequestForm()

    vendors = Vendor.query.order_by(Vendor.name).all()

    if flask_request.method == 'POST' and form.validate_on_submit():
        date_submitted = datetime.datetime.now()

        request_id = determine_fiscal_id(date_submitted)

        # determine what possible routes a request can take based on the request and the current user role
        current_status = status.NDA
        if current_user.role == roles.DIV:
            current_status = status.NCA
            if form.total_cost.data <= current_app.config['COST_LIMIT']:
                current_status = status.APR

        elif current_user.role == roles.COM:
            current_status = status.APR

        elif current_user.role == roles.PROC:
            current_status = status.NCA

        new_request = Request(
            request_id=request_id,
            division=current_user.division,
            date_submitted=date_submitted,
            item=form.item.data,
            quantity=form.quantity.data,
            unit_price=form.unit_price.data,
            total_cost=form.total_cost.data,
            funding_source=form.funding_source.data,
            funding_source_description=None,
            grant_name=None,
            project_name=None,
            justification=form.justification.data,
            status=current_status,
            creator_id=current_user.id
        )

        if new_request.funding_source == "Grant":
            new_request.grant_name = form.grant_name.data
            new_request.project_name = form.project_name.data
        elif new_request.funding_source == "Other":
            new_request.funding_source_description = form.funding_source_description.data

        request_vendor_name = str(form.request_vendor_name.data)
        request_vendor_phone = str(form.request_vendor_phone.data)
        request_vendor_fax = str(form.request_vendor_fax.data)
        request_vendor_mwbe = form.request_vendor_mwbe.data

        vendor_form = flask_request.form["request_vendor_dropdown"]
        if vendor_form == "default":
            new_vendor = Vendor(name=request_vendor_name,
                                address=form.request_vendor_address.data,
                                phone=request_vendor_phone,
                                fax=request_vendor_fax,
                                email=form.request_vendor_email.data,
                                tax_id=form.request_vendor_taxid.data,
                                mwbe=request_vendor_mwbe)
            db.session.add(new_vendor)
            db.session.commit()
            new_request.set_vendor_id(new_vendor.id)
        else:
            new_request.set_vendor_id(int(vendor_form))
        db.session.add(new_request)
        db.session.commit()

        # Email Notifications
        receivers, header = email_setup(current_user, new_request)

        send_email(receivers, header,
                   'request/new_request_notification',
                   user=current_user,
                   request=new_request)

        flash("Request was successfully created!")
        return redirect(url_for('request.display_request', request_id=new_request.id))

    else:
        print(form.errors)

    return render_template('request/new_request.html', form=form, user=current_user, vendors=vendors)


@request.route('/<request_id>', methods=['GET', 'POST'])
@login_required
def display_request(request_id):
    """Return page to view a specific request."""

    request = Request.query.filter_by(id=request_id).first()
    if current_user.role != roles.ADMIN and current_user.division != request.division:
        return redirect('requests')

    user = User.query.filter_by(id=request.creator_id).first()
    vendor = Vendor.query.filter_by(id=request.vendor_id).first()
    comments = Comment.query.filter_by(request_id=request_id).order_by(Comment.timestamp.desc()).all()

    comment_form = CommentForm()
    delete_form = DeleteCommentForm()
    status_form = StatusForm(status=request.status)

    allowed_to_update = True
    choices = []

    # determine what options the current user has for updating status
    if current_user.role == roles.REG:
        allowed_to_update = False

    elif current_user.role == roles.ADMIN:
        choices = [(status.NDA, status.NDA),
                   (status.NCA, status.NCA),
                   (status.APR, status.APR),
                   (status.DEN, status.DEN),
                   (status.RES, status.RES),
                   (status.HOLD, status.HOLD)]

    elif current_user.role == roles.DIV:
        approved = status.NCA
        if request.total_cost <= current_app.config['COST_LIMIT']:
            approved = status.APR

        choices = [(status.NDA, status.NDA),
                   (approved, "Approved"),
                   (status.DEN, status.DEN)]

        if request.status != status.NDA:
            allowed_to_update = False

    elif current_user.role == roles.COM:
        choices = [(status.NCA, status.NCA),
                   (status.APR, "Approved"),
                   (status.HOLD, status.HOLD),
                   (status.DEN, status.DEN)]

        if request.status != status.NDA and request.status != status.NCA:
            allowed_to_update = False

    elif current_user.role == roles.PROC:
        choices = [(status.NDA, status.NDA),
                   (status.NCA, status.NCA),
                   (status.APR, status.APR),
                   (status.DEN, status.DEN),
                   (status.RES, status.RES),
                   (status.HOLD, status.HOLD)]

    status_form.status.choices = choices

    if request:
        return render_template('request/request.html',
                               current_user=current_user,
                               request=request,
                               user=user,
                               vendor=vendor,
                               comments=comments,
                               comment_form=comment_form,
                               status_form=status_form,
                               delete_form=delete_form,
                               allowed_to_update=allowed_to_update)
    else:
        abort(404)


@request.route('/edit/<request_id>', methods=['GET', 'POST'])
@login_required
def edit_request(request_id):
    """Return page to edit a specific request."""
    if not current_user.role == roles.ADMIN:
        return redirect('requests')

    form = RequestForm()

    vendors = Vendor.query.order_by(Vendor.name).all()

    request, user, vendor = db.session.query(Request, User, Vendor).filter(Request.id == request_id). \
        filter(User.id == Request.creator_id). \
        filter(Request.vendor_id == Vendor.id).first()

    if flask_request.method == 'GET':
        form = RequestForm(item=request.item,
                           quantity=request.quantity,
                           unit_price=request.unit_price,
                           total_cost=request.total_cost,
                           funding_source=request.funding_source,
                           grant_name=request.grant_name,
                           project_name=request.project_name,
                           funding_source_description=request.funding_source_description,
                           justification=request.justification,
                           request_vendor_dropdown=str(request.vendor_id))

        return render_template('request/edit_request.html',
                               form=form,
                               vendors=vendors,
                               selected_vendor_id=vendor.id,
                               user=user,
                               request=request)

    elif flask_request.method == 'POST' and form.validate_on_submit():
        request.item = form.item.data
        request.quantity = form.quantity.data
        request.unit_price = form.unit_price.data
        request.total_cost = form.total_cost.data
        request.funding_source = form.funding_source.data
        request.justification = form.justification.data

        if request.funding_source == "Grant":
            request.grant_name = form.grant_name.data
            request.project_name = form.project_name.data
            request.funding_source_description = None
        elif request.funding_source == "Other":
            request.grant_name = None
            request.project_name = None
            request.funding_source_description = form.funding_source_description.data
        else:
            request.grant_name = None
            request.project_name = None

app/templates/request/comment_added.html
<p>
    {% if user.role != "Regular User" %}
    {{ user.role }}:
    {% endif %}
    {{ user.first_name }} {{ user.last_name }}
    has commented on Request {{ request_id }}:</p>
<p>{{ comment_form.content.data }}</p>
<p><a href="{{ url_for('request.display_request', request_id=request_id, _external=True) }}">Click here</a>
    to view this request.
</p>
<p>Sincerely,</p>
<p>The Procurement Team</p>
<p><small>Note: replies to this email address are not monitored.</small></p>

app/templates/request/new_request_notification.html
<p>
    Request {{ request.id }} (created by
    {% if user.role != "Regular User" %}
    {{ user.role }}:
    {% endif %}
    {{ user.first_name }} {{ user.last_name }})
    {% if request.status == "Needs Division Approval" %}
    has been routed for approval.
    {% elif request.status == "Needs Commissioner Approval" %}
    needs high level approval.
    {% endif %}
</p>
<p><a href="{{ url_for('request.display_request', request_id=request.id, _external=True) }}">Click here</a>
    to view this request.
</p>
<p>Sincerely,</p>
<p>The Procurement Team</p>
<p><small>Note: replies to this email address are not monitored.</small></p>

app/templates/request/request.html
{% extends "base.html" %}
{% block title %}
    Records Procurement - View Request
{% endblock title %}
{% block custom_css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-editable.css') }}"/>
{% endblock %}
{% block content %}

    <div class="page-header">
        <h1>{{ request.id }}</h1>
        {% if current_user.role == "Administrator" %}
            <a class="btn btn-primary btn-small" href="{{ url_for('request.edit_request', request_id=request.id) }}">Edit
                Request</a>
        {% endif %}
    </div>
    <div>
        <div class="col-sm-6">
            <div class="table-responsive">
                <table id="requests" class="table table-bordered table-striped">
                    <colgroup>
                        <col class="col-xs-2">
                        <col class="col-xs-4">
                    </colgroup>
                    <tbody id="request-table">
                    <tr>
                        <th scope="row" colspan="2">Request Information</th>
                    </tr>
                    <tr>
                        <th scope="row">Request ID:</th>
                        <td>{{ request.id }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Requester:</th>
                        <td><a href="mailto:{{ user.email }}">{{ user.name }}</a></td>
                    </tr>
                    <tr>
                        <th scope="row">Division:</th>
                        <td>{{ user.division }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Item:</th>
                        <td>{{ request.item }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Quantity:</th>
                        <td>{{ request.quantity }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Unit Price:</th>
                        <td>${{ request.unit_price }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Total Price:</th>
                        {% if request.total_cost %}
                            <td>${{ request.total_cost }}</td>
                        {% else %}
                            <td>$0.00</td>
                        {% endif %}
                    </tr>
                    <tr>
                        <th scope="row">Funding Source:</th>
                        <td>{{ request.funding_source }}</td>
                    </tr>
                    {% if request.funding_source == "Grant" %}
                        <tr>
                            <th scope="row">Grant Name:</th>
                            <td>{{ request.grant_name }}</td>
                        </tr>
                        <tr>
                            <th scope="row">Project Name:</th>
                            <td>{{ request.project_name }}</td>
                        </tr>
                    {% elif request.funding_source == "Other" %}
                        <tr>
                            <th scope="row">Funding Source Description:</th>
                            <td>{{ request.funding_source_description }}</td>
                        </tr>
                    {% endif %}
                    <tr>
                        <th scope="row">Justification:</th>
                        <td>{{ request.justification }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Status:</th>
                        <td>
                            {{ request.status }}
                            {% if allowed_to_update %}
                                <a class="btn btn-primary btn-sm pull-right"
                                   data-toggle="modal" data-target="#update_status">Update</a>
                            {% endif %}
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-sm-6">
            <div class="table-responsive">
                <table class="table table-bordered table-striped">
                    <colgroup>
                        <col class="col-xs-1">
                        <col class="col-xs-5">
                    </colgroup>
                    <tbody id="vendor-table">
                    <tr>
                        <th scope="row" colspan="2">Vendor Information</th>
                    </tr>
                    <tr>
                        <th scope="row">Name:</th>
                        <td>{{ vendor.name }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Address:</th>
                        <td>{{ vendor.address }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Phone:</th>
                        <td>{{ vendor.phone }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Fax:</th>
                        <td>{{ vendor.fax }}</td>
                    </tr>
                    <tr>
                        <th scope="row">Email:</th>
                        <td><a href="mailto:{{ vendor.email }}" id="vendor_email">{{ vendor.email }}</a></td>
                    </tr>
                    <tr>
                        <th scope="row">Tax ID:</th>
                        <td>{{ vendor.tax_id }}</td>
                    </tr>
                    <tr>
                        <th scope="row">M/WBE:</th>
                        {% if vendor.mwbe %}
                            <td>Yes</td>
                        {% else %}
                            <td>No</td>
                        {% endif %}
                    </tr>
                    </tbody>
                </table>
                <a class="btn btn-primary btn-small"
                   href="{{ url_for('request.display_requests') }}">Return to Request History</a>
            </div>
        </div>
    </div>

    <!-- Modal -->
    {% if allowed_to_update %}
        <div id="update_status" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">{{ current_user.role }}: Update Status</h4>
                    </div>
                    <div class="modal-body">

                        <form action="{{ url_for('request.update_status', request_id=request.id) }}"
                              name="update_status" class="form-horizontal" id="status" method="POST">

                            {{ status_form.hidden_tag() }}

                            <div class="form-group row">
                                <label for="quantity" class="col-sm-3 form-control-label">New Status</label>
                                <div class="col-sm-5">
                                    {{ status_form.status }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-sm-5">
                                    {{ status_form.submit(class="btn btn-primary btn-small") }}
                                </div>
                            </div>

                        </form>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    {% endif %}

    <div style="display: inline-block; width: 100%;">
        <h3>Comments</h3>
        {% if current_user.role != "Regular User" or current_user.id == request.creator_id %}
            <div class="form-group col">
                <form action="{{ url_for('request.add_comment', request_id=request.id) }}" method="post"
                      enctype="multipart/form-data">
                    {{ comment_form.hidden_tag() }}
                    {{ comment_form.content(id="note", rows="3", cols="100", maxlength="500") }}
                    {{ comment_form.file }} <br>
                    {{ comment_form.submit(class="btn btn-primary btn-small") }}
                </form>
            </div><br>
        {% endif %}
        {% if comments | length != 0 %}
            {% for comment in comments %}
                <div class="well">
                    <form action="{{ url_for('request.delete_comment') }}"
                          method="post" value="{{ comment.id }}">
                        <label>{{ comment.timestamp.strftime("%m/%d/%Y %I:%M:%S %p") }} |
                            {% if comment.user.role != "Regular User" %}
                                {{ comment.user.role }}:
                            {% endif %}
                            {{ comment.user.first_name }} {{ comment.user.last_name }}
                            {% if comment.user_id == current_user.id %}
                                (You)
                            {% elif comment.user_id == request.creator_id %}
                                (Creator)
                            {% endif %}
                        </label>
                        {% if (current_user.role == "Administrator" or current_user.id == comment.user_id) and comment.editable %}
                            {{ delete_form.request_id(value=request.id) }}
                            {{ delete_form.comment_id(value=comment.id) }}
                            {{ delete_form.submit(class="btn btn-danger btn-small", style="float: right;") }}
                        {% endif %}
                    </form>
                    <div>{{ comment.content }}</div>
                    {% if comment.filepath %}
                        <div>
                            <a href="{{ url_for('request.download', comment_id=comment.id) }}">{{ comment.filepath[13:] }}</a>
                        </div>
                    {% endif %}
                </div><br>
            {% endfor %}
        {% else %}
            <div class="well">There are currently no comments.</div>
        {% endif %}
    </div>

{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-2.0.3.min.js"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins/bootstrap-editable.js') }}"></script>
    {% block request_xeditable %}
        {#        {% include "request/request_x-editable.html" %}#}
    {% endblock %}
{% endblock %}

app/templates/request/requests.html
{% extends "base.html" %}
{% block title %}
    Records Procurement - Request History
{% endblock title %}
{% block custom_css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/plugins/bootstrap-table.min.css') }}">
{% endblock custom_css_links %}

{% block content %}
    <div class="page-header">
        <div class="row">
            <div class="col-sm-5">
                <h2>Request History</h2>
            </div>
            <div class="col-sm-offset-4 col-sm-3">
                <a href="{{ url_for('request.new_request') }}" class="btn btn-primary btn-large pull-right">New
                    Request</a>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <table id="display_requests" class="table table-nonfluid table-hover"
                   style="border-collapse:collapse"
                   data-toggle="table"
                   data-search="true"
                   data-show-refresh="true"
                   data-show-toggle="true"
                   data-show-columns="true"
                   data-filter-control="true"
                   data-pagination="true"
                   data-side-pagination="client"
                   data-page-list="[5, 10, 20, 50, 100, 200]"
                   data-show-export="true"
                   data-toolbar="#toolbar">

                <thead>
                <tr>
                    <th data-field="id" class="col-sm-1" data-sortable="true">Request #</th>
                    <th class="col-sm-1" data-field="date" data-sortable="true">Date Submitted</th>
                    <th class="col-sm-2" data-field="division" data-sortable="true" data-filter-control="select">
                        Division
                    </th>
                    <th class="col-sm-5" data-sortable="false">Request Description</th>
                    <th class="col-sm-2" data-sortable="true">Status</th>
                    <th class="col-sm-1" data-sortable="false">Total Cost</th>
                    {% if current_user.role == "Administrator" %}
                        <th class="col-sm-1" data-sortable="false">Edit</th>
                    {% endif %}
                    <th class="col-sm-1" data-sortable="false">View</th>
                </tr>
                </thead>
                <tbody>
                {% for request in requests %}
                    <tr id="request-row" class="table-row" data-href="/requests/{{ request.id }}">
                        <td> {{ request.id }} </td>
                        <td> {{ request.date_submitted.date() }} </td>
                        <td> {{ request.division }} </td>
                        <td> {{ request.item }} </td>
                        <td> {{ request.status }} </td>
                        <td> ${{ request.total_cost }} </td>
                        {% if current_user.role == "Administrator" %}
                            <td><a class="btn btn-danger btn-small" href="/requests/edit/{{ request.id }}">Edit</a></td>
                        {% endif %}
                        <td><a class="btn btn-primary btn-small" href="/requests/{{ request.id }}">View</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="spacer"></div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-2.0.3.min.js"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap-table.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap-table-filter-control.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap-table-export.min.js') }}"></script>
    <script src="//rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js"></script>
{#    <script type="text/javascript">#}
{#        $(document).ready(function ($) {#}
{#            $(".table-row").click(function () {#}
{#                window.location = $(this).data("href");#}
{#            });#}
{#        });#}
{#    </script>#}
{% endblock %}