app/main/forms.py
"""
.. module:: main.forms.

    :synopsis: Defines forms used to create procurement requests
"""
from flask import Flask
from flask_wtf import Form
from wtforms import StringField, SelectField, TextAreaField, SubmitField, BooleanField, DecimalField, IntegerField
from wtforms.validators import DataRequired, Length, Email
from wtforms_alchemy import PhoneNumberField
from app.constants import division, roles

app = Flask(__name__)

funding = [
    ('', ''),
    ('Expense', 'Expense'),
    ('MAARF', 'MAARRF'),
    ('Grant', 'Grant'),
    ('KOCH', 'KOCH'),
    ('Other', 'Other')
]

divisions = [(division.MRMD, division.MRMD),
             (division.ARC, division.ARC),
             (division.GRA, division.GRA),
             (division.LIB, division.LIB),
             (division.EXEC, division.EXEC),
             (division.TECH, division.TECH),
             (division.ADM, division.ADM)]

roles = [(roles.REG, roles.REG),
         (roles.DIV, roles.DIV),
         (roles.COM, roles.COM),
         (roles.PROC, roles.PROC),
         (roles.ADMIN, roles.ADMIN)]


class RequestForm(Form):
    """Form for creating a new request."""
    request_name = StringField(u'Name*(required)')
    division = SelectField(u'Division*', choices=divisions, default='')
    item = TextAreaField(u'Item*(required)')
    quantity = IntegerField(u'Quantity*', validators=[DataRequired('Please enter the quantity')])
    unit_price = DecimalField(u'Price per item*', validators=[DataRequired('Please enter the price per item')])
    total_cost = DecimalField(u'Total price*', validators=[DataRequired('Please enter the total price')])
    funding_source = SelectField(u'Funding*', choices=funding,
                                 validators=[DataRequired('Please select the funding source')])
    funding_source_description = StringField(u'Funding Other')
    grant_name = StringField(u'Grant Name')
    project_name = StringField(u'Project Name')
    justification = TextAreaField(u'Justification*(required)', validators=[
        DataRequired('You must enter a justification for your request'), Length(1, 500)])
    request_vendor_name = StringField(u'Vendor Name')
    request_vendor_address = StringField(u'Vendor Address')
    request_vendor_phone = PhoneNumberField(region='US', display_format='national')
    request_vendor_fax = PhoneNumberField(region='US', display_format='national')
    request_vendor_email = StringField(u'Email')
    request_vendor_taxid = StringField(u'Vendor Tax ID')
    request_vendor_mwbe = BooleanField(u'mwbe')
    submit = SubmitField(u'Submit Request')


class UserForm(Form):
    """Form for creating a new user."""
    first_name = StringField('first_name', validators=[DataRequired(), Length(1, 100)])
    last_name = StringField('last_name', validators=[DataRequired(), Length(1, 100)])
    division = SelectField('division', validators=[DataRequired()], choices=divisions)
    email = StringField('Email', validators=[DataRequired(), Length(1, 100), Email()])
    phone = PhoneNumberField('Phone', region='US', display_format='national', validators=[DataRequired()])
    address = StringField('Address', validators=[DataRequired()])
    submit = SubmitField(u'Create User')


class EditUserForm(Form):
    """Form for updating user information."""
    user_first_name = StringField(u'First Name*(required)', validators=[DataRequired(), Length(1, 100)])
    user_last_name = StringField(u'Last Name*(required)', validators=[DataRequired(), Length(1, 100)])
    user_role = SelectField('role', validators=[DataRequired()], choices=roles)
    user_division = SelectField('division', validators=[DataRequired()], choices=divisions)
    user_email = StringField(u'Email*(required)', validators=[DataRequired(), Length(1, 100), Email()])
    user_phone = PhoneNumberField('Phone', region='US', display_format='national', validators=[DataRequired()])
    user_address = StringField('Address', validators=[DataRequired()])
    update = SubmitField(u'Update Information')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/main/views.py
"""
.. module:: main.views.

    :synopsis: Handles all core URL endpoints for the procurement application
"""
from flask import render_template, request, redirect, url_for, jsonify, flash
from flask_login import login_required, current_user
from app import db
from app.models import Vendor, User
from app.main import main
from app.main.forms import UserForm, EditUserForm
from app.constants import roles


@main.route('/')
def index():
    """Return homepage with a button redirecting to the procurement request history."""
    return render_template('main/index.html')


@main.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    """Displays user information (redirects to profile page)."""
    return render_template('main/profile.html',
                           current_user=current_user)


@main.route('/profile/edit', methods=['GET', 'POST'])
@login_required
def edit_profile():
    """Allows a user to edit their own information"""
    form = EditUserForm(user_role=current_user.role)
    if request.method == 'POST':
        if form.validate_on_submit():
            if current_user.email == form.user_email.data or \
                            len(User.query.filter_by(email=form.user_email.data).all()) == 0:
                user_first_name = form.user_first_name.data
                user_last_name = form.user_last_name.data
                user_role = form.user_role.data
                user_email = form.user_email.data
                user_phone = str(form.user_phone.data)
                user_address = form.user_address.data
                current_user.first_name = user_first_name
                current_user.last_name = user_last_name
                current_user.role = user_role
                current_user.email = user_email
                current_user.phone = user_phone
                current_user.address = user_address
                db.session.commit()
                flash('User information successfully updated!')
                return redirect(url_for('main.profile'))
            else:
                flash('User email already exists.')
        else:
            print(form.errors)
    return render_template('main/edit_user.html', user=current_user, form=form)


@main.route('/profile/reset', methods=['GET', 'POST'])
@login_required
def profile_password_reset():
    """Allows a user to reset their password from their profile"""
    token = current_user.generate_reset_token()
    return redirect(url_for('auth.password_reset', token=token))


@main.route('/divisions', methods=['GET'])
def divisions():
    divisions = {
        'MRMD': 'MRMD',
        'Archives': 'Archives',
        'Grants': 'Grants',
        'Library': 'Library',
        'Executive': 'Executive',
        'Tech': 'Tech',
        'Administration': 'Administration'
    }
    return jsonify(divisions)


@main.route('/parse_vendor', methods=['GET'])
def jsonify_fields():
    if request.args['vendor'] == "default":
        return jsonify("")
    v = Vendor.query.filter_by(id=int(request.args['vendor'])).first()
    return jsonify(v.name, v.address, v.phone, v.fax, v.email, v.tax_id, v.mwbe)


@main.route('/manage_users', methods=['GET', 'POST'])
@login_required
def manage_users():
    """Return the admin panel where admins can create users, edit user information, and update login privileges."""
    if not current_user.role == roles.ADMIN:
        return redirect('requests')

    users = User.query.filter(User.id != current_user.id).order_by(User.last_name).all()
    form = UserForm()
    errors = False
    if request.method == 'POST':
        if form.validate_on_submit():
            new_user = User(email=form.email.data.lower(),
                            phone=str(form.phone.data),
                            address=form.address.data,
                            division=form.division.data,
                            password='Change4me',
                            first_name=form.first_name.data,
                            last_name=form.last_name.data)
            db.session.add(new_user)
            db.session.commit()
            flash('User account successfully created!')
            return redirect(url_for('main.manage_users'))
        else:
            print(form.errors)
            errors = True
    return render_template('main/manage_users.html', users=users, form=form, errors=errors)


@main.route('/manage_users/users/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_user(id):
    """Return the page for an admin to update user information."""
    if not current_user.role == roles.ADMIN:
        return redirect('requests')

    user = User.query.get_or_404(id)
    form = EditUserForm(user_role=user.role, user_division=user.division)
    if request.method == 'POST':
        if form.validate_on_submit():
            if user.email == form.user_email.data or len(User.query.filter_by(email=form.user_email.data).all()) == 0:
                user_first_name = form.user_first_name.data
                user_last_name = form.user_last_name.data
                user_role = form.user_role.data
                user_division = form.user_division.data
                user_email = form.user_email.data
                user_phone = str(form.user_phone.data)
                user_address = form.user_address.data
                user.first_name = user_first_name
                user.last_name = user_last_name
                user.role = user_role
                user.division = user_division
                user.email = user_email
                user.phone = user_phone
                user.address = user_address
                db.session.commit()
                flash('User information successfully updated!')
                return redirect(url_for('main.manage_users'))
            else:
                flash('User email already exists.')
        else:
            print(form.errors)
    return render_template('main/edit_user.html', user=user, form=form)


@main.route('/manage_users/users/reset/<int:id>', methods=['GET', 'POST'])
@login_required
def reset_password(id):
    """Resets the password of the user and then redirects to the edit user page."""
    if not current_user.role == roles.ADMIN:
        return redirect('requests')

    user = User.query.get_or_404(id)
    user.password = 'Change4me'
    db.session.commit()
    flash('User password was successfully reset!')
    return redirect(url_for('main.edit_user', id=id))


@main.route('/manage_users/users/disable/<int:id>', methods=['GET', 'POST'])
@login_required
def disable(id):
    """Disables the user's login privileges and redirects to admin panel page."""
    if not current_user.role == roles.ADMIN:
        return redirect('requests')

    user = User.query.get_or_404(id)
    user.login = False
    db.session.commit()
    flash('User login privileges have been disabled.')
    return redirect(url_for('main.manage_users'))


@main.route('/manage_users/users/enable/<int:id>', methods=['GET', 'POST'])
@login_required
def enable(id):
    """Enables the user's login privileges and redirects to admin panel page."""
    if not current_user.role == roles.ADMIN:
        return redirect('requests')

    user = User.query.get_or_404(id)
    user.login = True
    db.session.commit()
    flash('User login privileges have been enabled.')
    return redirect(url_for('main.manage_users'))

app/templates/main/edit_user.html
<!-- This template is to initiate a new request. -->
{% extends "base.html" %} {% block title %}Records Procurement - Edit User Information{% endblock title %}
{% block custom_css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
{% endblock custom_css_links %}
{% block content %}
    <div class="page-header">
        <!-- start of static form -->
        <h1>Edit User Information</h1>
    </div>
    <p><i><strong>User Information</strong></i></p>

    <br>

    <form name="edit_user" class="form-horizontal" id="updateUser" method="POST" action="">
        {{ form.hidden_tag() }}

        <div class="form-group row">
            {% for message in form.user_first_name.errors %}
                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
            {% endfor %}

            <label for="quantity" class="col-sm-3 form-control-label">User First Name</label>
            <div class="col-sm-5">
                {{ form.user_first_name(id="user_first_name", class="form-control", type="text", value=user.first_name) }}
                <div class="small">Edit first name if applicable.</div>
            </div>
        </div>

        <div class="form-group row">
            {% for message in form.user_last_name.errors %}
                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
            {% endfor %}

            <label for="quantity" class="col-sm-3 form-control-label">User Last Name</label>
            <div class="col-sm-5">
                {{ form.user_last_name(id="user_last_name", class="form-control", type="text", value=user.last_name) }}
                <div class="small">Edit last name if applicable.</div>
            </div>
        </div>

        {% if current_user.id != user.id %}
        <div class="form-group row">
            {% for message in form.user_last_name.errors %}
                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
            {% endfor %}

            <label for="quantity" class="col-sm-3 form-control-label">User Role</label>
            <div class="col-sm-5">
                {{ form.user_role(id="user_role", class="form-control", default=user.role) }}
                <div class="small">Edit role if applicable.</div>
            </div>
        </div>
        {% endif %}

        <div class="form-group row">
            {% for message in form.user_division.errors %}
                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
            {% endfor %}

            <label for="quantity" class="col-sm-3 form-control-label">User Division</label>
            <div class="col-sm-5">
                {{ form.user_division(id="user_division", class="form-control", default=user.division) }}
                <div class="small">Edit division if applicable.</div>
            </div>
        </div>

        <div class="form-group row">
            {% for message in form.user_email.errors %}
                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
            {% endfor %}

            <label for="quantity" class="col-sm-3 form-control-label">User Email</label>
            <div class="col-sm-5">
                {{ form.user_email(id="user_email", class="form-control", type="text", value=user.email) }}
                <div class="small">Edit email if applicable.</div>
            </div>
        </div>

        <div class="form-group row">
            {% for message in form.user_phone.errors %}
                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
            {% endfor %}

            <label for="quantity" class="col-sm-3 form-control-label">User Phone Number</label>
            <div class="col-sm-5">
                {{ form.user_phone(id="user_phone", class="form-control", type="text", value=user.phone) }}
                <div class="small">Edit phone number if applicable.</div>
            </div>
        </div>

        <div class="form-group row">
            {% for message in form.user_address.errors %}
                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
            {% endfor %}

            <label for="quantity" class="col-sm-3 form-control-label">User Address</label>
            <div class="col-sm-5">
                {{ form.user_address(id="user_address", class="form-control", type="text", value=user.address) }}
                <div class="small">Edit address if applicable.</div>
            </div>
        </div>

        {% if current_user.id != user.id %}
        <div class="form-group row">
            <label for="quantity" class="col-sm-3 form-control-label">Reset Password</label>
            <div class="col-sm-5">
                <a class="btn btn-danger btn-small" href="/manage_users/users/reset/{{ user.id }}">Reset Password</a>
                <div class="small">Click to reset user password.</div>
            </div>
        </div>
        {% endif %}

        <div class="form-group row">
            <div class="spacer">
                <button type="submit" class="btn btn-primary btn-lg btn-block">Save Changes</button>
            </div>
        </div>

    </form>
    <!-- end of static form -->
{% endblock %}

{% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% block title %}Records Procurement - Home{% endblock title %}
{% block content %}
    <div class="jumbotron">
        <h1>Procurement App</h1>
        <p class="lead"></p>
        <p><a class="btn btn-lg btn-success" href="/requests" role="button">Start</a>
        </p>
    </div>
{% endblock %}

app/templates/main/manage_users.html
{% extends "base.html" %}
{% block title %}
    Records Procurement - Manage Users
{% endblock title %}
{% block custom_css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/plugins/bootstrap-table.min.css') }}">
{% endblock custom_css_links %}

{% block content %}
    <div class="page-header">
        <div class="row">
            <div class="col-sm-5">
                <h2>Manage Users</h2>
            </div>
            <div class="col-sm-offset-4 col-sm-3">
                <a class="btn btn-primary btn-large pull-right" data-toggle="modal" data-target="#createUser">Create
                    User</a>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div id="createUser" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Create New User</h4>
                </div>
                <div class="modal-body">

                    <form novalidate="new_user" class="form-horizontal" id="submitUser" method="POST">

                        {{ form.hidden_tag() }}

                        <div class="form-group row">
                            {% for message in form.first_name.errors %}
                                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
                            {% endfor %}

                            <label for="quantity" class="col-sm-3 form-control-label">User First Name</label>
                            <div class="col-sm-5">
                                {{ form.first_name(id="user_first_name", class="form-control", type="text") }}
                                <div class="small">First name is required.</div>
                            </div>
                        </div>

                        <div class="form-group row">
                            {% for message in form.last_name.errors %}
                                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
                            {% endfor %}

                            <label for="quantity" class="col-sm-3 form-control-label">User Last Name</label>
                            <div class="col-sm-5">
                                {{ form.last_name(id="user_last_name", class="form-control", type="text") }}
                                <div class="small">Last name is required.</div>
                            </div>
                        </div>

                        <div class="form-group row">
                            {% for message in form.division.errors %}
                                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
                            {% endfor %}

                            <label for="quantity" class="col-sm-3 form-control-label">Division</label>
                            <div class="col-sm-5">
                                {{ form.division(id="user_division", class="form-control", type="text") }}
                                <div class="small">Division is required.</div>
                            </div>
                        </div>

                        <div class="form-group row">
                            {% for message in form.email.errors %}
                                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
                            {% endfor %}

                            <label for="quantity" class="col-sm-3 form-control-label">User Email</label>
                            <div class="col-sm-5">
                                {{ form.email(id="user_email", class="form-control", type="text") }}
                                <div class="small">Email is required.</div>
                            </div>
                        </div>

                        <div class="form-group row">
                            {% for message in form.phone.errors %}
                                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
                            {% endfor %}

                            <label for="quantity" class="col-sm-3 form-control-label">User Phone Number</label>
                            <div class="col-sm-5">
                                {{ form.phone(id="user_phone", class="form-control", type="text") }}
                                <div class="small">Phone number is required.</div>
                            </div>
                        </div>

                        <div class="form-group row">
                            {% for message in form.address.errors %}
                                <div class="alert alert-danger" id="missing_quantity">{{ message }}</div>
                            {% endfor %}

                            <label for="quantity" class="col-sm-3 form-control-label">User Address</label>
                            <div class="col-sm-5">
                                {{ form.address(id="user_address", class="form-control", type="text") }}
                                <div class="small">Address is required.</div>
                            </div>
                        </div>

                        <div class="form-group row">
                            <div class="spacer">
                                <button type="submit" class="btn btn-primary btn-lg btn-block">Create User</button>
                            </div>
                        </div>

                    </form>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>

        </div>
    </div>

    <div id="test" class="row">
        <div class="col-lg-12">
            <table id="display_users" class="table table-nonfluid table-hover"
                   style="border-collapse:collapse"
                   data-toggle="table"
                   data-search="true"
                   data-show-refresh="true"
                   data-show-toggle="true"
                   data-show-columns="true"
                   data-filter-control="true"
                   data-pagination="true"
                   data-side-pagination="client"
                   data-page-list="[5, 10, 20, 50, 100, 200]"
                   data-show-export="true"
                   data-toolbar="#toolbar">

                <thead>
                <tr>
                    <th class="col-sm-1" data-field="name" data-sortable="true">Name</th>
                    <th class="col-sm-1" data-field="email" data-sortable="true">Email</th>
                    <th class="col-sm-1">User Information</th>
                    <th class="col-sm-1">Login Privileges</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr class="table-row">
                        <td> {{ user.first_name }} {{ user.last_name }} </td>
                        <td> {{ user.email }} </td>
                        <td><a class="btn btn-primary btn-small" href="/manage_users/users/{{ user.id }}">Edit</a></td>
                        <td>
                            {% if user.login == True %}
                                Enabled
                                <a class="btn btn-danger btn-small pull-right"
                                   href="/manage_users/users/disable/{{ user.id }}">Disable</a></td>
                            {% else %}
                                Disabled
                                <a class="btn btn-primary btn-small pull-right"
                                   href="/manage_users/users/enable/{{ user.id }}">Enable</a></td>
                            {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
            <div class="spacer"></div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-2.0.3.min.js"></script>
    <script type="text/javascript">
        var formErrors = {% if form.errors %}true{% else %}false{% endif %};

        $(document).ready(function () {
            if (formErrors) {
                $('.modal').modal('show');
            }
        });
    </script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap-table.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap-table-filter-control.min.js') }}"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap-table-export.min.js') }}"></script>
    <script src="//rawgit.com/hhurz/tableExport.jquery.plugin/master/tableExport.js"></script>
{% endblock %}

app/templates/main/profile.html
{% extends "base.html" %}
{% block title %}
    Records Procurement - View Request
{% endblock title %}
{% block custom_css_links %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-editable.css') }}"/>
{% endblock %}
{% block content %}

    <div class="page-header">
        <h1>{{ current_user.first_name}} {{ current_user.last_name }}</h1>
        <a class="btn btn-primary btn-small" href="{{ url_for('main.edit_profile') }}">Edit
            Information</a>
        <a class="btn btn-primary btn-danger" href="{{ url_for('main.profile_password_reset') }}">Reset Password</a>
    </div>

    <div class="col-sm-push-12">
        <div class="table-responsive">
            <table id="requests" class="table table-bordered table-striped">
                <colgroup>
                    <col class="col-xs-4">
                    <col class="col-xs-8">
                </colgroup>
                <tbody>
                <tr>
                    <th scope="row" colspan="2">User Information</th>
                </tr>
                <tr>
                    <th scope="row">First Name:</th>
                    <td>{{ current_user.first_name }}</td>
                </tr>
                <tr>
                    <th scope="row">Last Name:</th>
                    <td>{{ current_user.last_name }}</td>
                </tr>
                <tr>
                    <th scope="row">Email:</th>
                    <td><a href="mailto:{{ current_user.email }}">{{ current_user.email }}</a></td>
                </tr>
                <tr>
                    <th scope="row">Phone Number:</th>
                    <td>{{ current_user.phone }}</td>
                </tr>
                <tr>
                    <th scope="row">Address:</th>
                    <td>{{ current_user.address }}</td>
                </tr>
                <tr>
                    <th scope="row">Division:</th>
                    <td>{{ current_user.division }}</td>
                </tr>
                <tr>
                    <th scope="row">Role:</th>
                    <td>{{ current_user.role }}</td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="https://code.jquery.com/jquery-2.0.3.min.js"></script>
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/plugins/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins/bootstrap-editable.js') }}"></script>
    {% block request_xeditable %}
{#        {% include "request/request_x-editable.html" %}#}
    {% endblock %}
{% endblock %}